metric:
  #node_name: '' # defaults to hostname
  period: 10s

log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "info"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "error"
  agent:
    enabled: false
    dsn: 'udp://logstash.example.com:8911'
    app_id: minimetric
    #host: '' # log host, defaults to os.Getenv("HOST") or os.Hostname()
    #instance_id: '' # log instance_id, defaults to os.Getenv("INSTANCE_ID") or os.Hostname()

output:
  logstash:
    hosts: ['logstash.example.com:5044']

kubernetes:
  in_cluster: false # default: false
  config: '~/.kube/config'
